# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
    release:
      types: [published]  # 'published' ist besser als 'created'
    workflow_dispatch:    # Erlaubt manuelles Auslösen

  jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18, 20, 22]  # Teste auf mehreren Versionen
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'  # Cache für schnellere Builds
        - run: npm ci
        - run: npm test
        - run: npm audit --production  # Security Check

    publish-npm:
      needs: test  # Nur publishen wenn Tests erfolgreich
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: https://registry.npmjs.org/
            cache: 'npm'
        - run: npm ci

        # Version Check - stelle sicher dass Tag und package.json übereinstimmen
        - name: Check versions match
          run: |
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
              echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
              exit 1
            fi

        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}  # Groß geschrieben ist Konvention
